### ISSUE TITLE
Arquivo main.py

### ISSUE THREAD

**Issue by marquesdiegoo** [cristianovisk/regvuln#1]
Tudo bem Cristiano no seu projeto nao tem o arquivo main.py e no seu tutorial manda execultar ele qual seria o que podemos usar? 
Muito obrigado por compartilhar.

**Comment by cristianovisk** [comment]
Olá Diego, o novo main é o regvuln.py vou atualizar na Doc

**Comment by cristianovisk** [comment]
Atualizei a doc obrigado pelo feedback

**Comment by marquesdiegoo** [comment]
Mano estou rodando pythin3 regvuln.py  não mostra nada na tela, no arquivo de log que é criado aparece isso: 
![image](https://user-images.githubusercontent.com/56923760/196076769-d70fe5bc-bf3d-4242-b3dd-8d3535f1b647.png)

**Comment by cristianovisk** [comment]
Tem que ser 'python3 regvuln.py --run' tem mais informações no --help

**Comment by cristianovisk** [comment]
acabei de atualizar com algumas correções e a função de cache de imagens

**Comment by marquesdiegoo** [comment]
Mano esse link ta correto: 

![image](https://user-images.githubusercontent.com/56923760/196227799-4798d36e-862b-46dd-a699-e252a5353412.png)

**Comment by cristianovisk** [comment]
Corrigido já, obrigado pelos feedbacks, a documentação tava desatualizada antes de lançar.
